Template folder
SaharNaderi/pink-elephant pull request #38
Opened 2023-07-26 17:22 UTC by ManaGh

Template folder in src folder created & PageTemplate.js established

2023-07-27 08:31 UTC, Ali-Jahankah requested changes

2023-07-27 08:31 UTC, Ali-Jahankah commented on client/src/template/PageTemplate.js
> +export default PageTemplate;
Please DON'T USE ChatGPT.
We want responsive design with 3 parts: header, main and footer.
Each component must have one css file and write it's styles in that css file.
So, NO CSS IN JS FILE.
Pease create header and footer for the template. It's not empty in the design.
We don't need children, we need OutLet tag instead.

You MUST LEARN React Router 6 and have a good knowledge of css and flexbox.

2023-07-28 02:01 UTC, ManaGh commented on client/src/template/PageTemplate.js
> +export default PageTemplate;
I am so apriciated for your amazing guidence.
I studied the Router 6 and I hard work on my code so I commit the new version of that with React Router but this is just the js part ( when you proved I'm in a write way I'll commit the css part )

2023-07-28 12:15 UTC, Ali-Jahankah requested changes

2023-07-28 12:40 UTC, ManaGh commented on client/src/template/PageTemplate.js
> +							</div>
I didn't use chat gpt for this part I used the w3 schools and stack overflow because you said just for error we can use it

2023-07-28 12:46 UTC, ManaGh commented on client/src/App.js
> +
oh, I get it

2023-08-02 08:28 UTC, closed without merging