23-Feat/add-constants-Leila
SaharNaderi/pink-elephant pull request #40
Opened 2023-07-27 14:27 UTC by leilafarsani

This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

This pull request organizes server code, adds a "constants" folder, and replaces hard-coded strings with constants for better maintainability.

### Related to

Feat #23 

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have carefully reviewed my own code
- [ ] I have commented my code
- [X] I have updated any documentation
- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [ ] I have requested reviewers here and in my team chat channel

2023-07-27 14:38 UTC, Ali-Jahankah requested changes

2023-07-27 14:38 UTC, Ali-Jahankah commented on client/src/index.js
We don't need these in this PR.

2023-07-27 14:38 UTC, Ali-Jahankah commented on client/src/styles/index.css
> +}
None of these changes needed.

2023-07-27 14:38 UTC, Ali-Jahankah commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
Have you loged this const in the app to see if it's working or not? As Node doesn't support 'export'.
TS supports that but this starter kit may support that or may not as it's using Webpack compiler!
Test it and update me. Thanks!

2023-07-27 15:50 UTC, leilafarsani commented on client/src/index.js
It's from other brach :(

2023-07-27 15:50 UTC, leilafarsani commented on client/src/styles/index.css
> +}
like above :))

2023-07-27 16:01 UTC, Ali-Jahankah commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
Ok fine. So, files must be ".js".
log that as you are using "export const ..."; if you get undefined, then use "module.exports={name of the consts}" and it should work.
@leilafarsani

2023-07-27 16:02 UTC, leilafarsani commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
I meant I can btw in the other comment, sorry 🤣

2023-07-27 16:10 UTC, Ali-Jahankah commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
Ok fine. Please, we don't need to change any configs. This starter kit is created at the highest standard of it.
So fix it and change the PR to staging branch, then we can merge it. Thanks!

2023-07-27 16:12 UTC, leilafarsani commented on client/src/index.js
Yes TL 🫡

2023-07-27 16:13 UTC, leilafarsani commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
Yes TL 🫡

2023-07-27 21:38 UTC, leilafarsani commented on server/constants/pathConstants.js
> +export const GET_USERS_PATH = "/get-users";
I cleaned the mess.
It is also tested in api.js file 
![IMAGE 2023-07-27 22:36:30](https://github.com/SaharNaderi/pink-elephant/assets/108967493/5c5863a8-60a6-4210-b111-b0afe078d4a0)

2023-07-28 08:27 UTC, Ali-Jahankah approved these changes
Nice work!

2023-07-28 08:27 UTC, merged