24-Feat/add-schema-file-and-users-table
SaharNaderi/pink-elephant pull request #41
Opened 2023-07-27 19:23 UTC by leilafarsani

This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

Description:
In this pull request, we introduce the initial setup for the "users" table and its associated schema definition. The changes include the creation of the "users_schema.sql" file, which contains the necessary SQL code to create the table with appropriate columns.

The SQL code in "users_schema.sql" has been tested and executed successfully in a local PostgreSQL database.

### How to test:

- connect to the database 
- Type `SELECT * FROM users; ` in the terminal
- check the the user table and its column.

### Related to

Feat #24 

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have carefully reviewed my own code
- [ ] I have commented my code
- [X] I have updated any documentation
- [X] I have written a title that reflects the relevant ticket
- [X] I have written a description that says what the PR does and how to validate it
- [X] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [X] I have added a link to this PR to the ticket
- [ ] I have requested reviewers here and in my team chat channel

2023-07-27 23:18 UTC, Ali-Jahankah requested changes

2023-07-27 23:18 UTC, Ali-Jahankah commented on server/schema/users_schema.sql
> +    description VARCHAR(500) NOT NULL,
No more than 255

2023-07-27 23:18 UTC, Ali-Jahankah commented on server/schema/users_schema.sql
> +
Nice work but Better to set default values for optional fields to '__' for writing less error handling codes in Front End and showing in the app. So just use DEFAULT and give them default values.

2023-07-27 23:31 UTC, leilafarsani commented on server/schema/users_schema.sql
> +
Many thanks for the review! Done!

2023-07-28 08:21 UTC, Ali-Jahankah commented
Nice work!

2023-07-28 08:22 UTC, merged