feat-colorpallet
SaharNaderi/pink-elephant pull request #44
Opened 2023-07-28 09:58 UTC by SaharNaderi

<img width="1037" alt="Screenshot 2023-07-28 at 10 43 10" src="https://github.com/SaharNaderi/pink-elephant/assets/108987674/5d95d9ba-c9f7-4c9f-8a4d-3b0715222d4d">
Colorpallet import and cheacked.

2023-07-28 10:21 UTC, Ali-Jahankah requested changes
Nice work, just a minor comment regarding names. Nice screenshot.

2023-07-28 10:21 UTC, Ali-Jahankah commented on client/src/styles/colors.css
> +}
All the names must be changed to real simple names like: red, blue, darkBlue, brown,...

2023-07-30 16:39 UTC, SaharNaderi commented
updated name of color pallet.
<img width="1440" alt="Screenshot 2023-07-30 at 14 36 41" src="https://github.com/SaharNaderi/pink-elephant/assets/108987674/674bedfc-d2b2-4013-a30d-40c88551c2ae">

2023-07-31 19:26 UTC, ManaGh approved these changes

2023-07-31 19:29 UTC, merged